version: '3'


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Construction de l'image Docker"
    - docker build -t monapp:latest . 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 
    - docker push $CI_REGISTRY_IMAGE  # Pousser l'image vers le registre Docker
  only:
    - master  

test:
  stage: test
  script:
    - echo "Ex

